account/urls.py
# django library
from django.urls import path

# my views
from account import views


urlpatterns = [

    # admin view
    path('admin-site/', views.AdminView.as_view(), name='admin_site'),

    # create user view
    path('create-user/', views.CreateNewUser.as_view(), name='create_user'),

    # change medical user data
    path('medical-user-data-change/<int:md_id>/', views.MedicalUserDataChange.as_view(), name='medical_user_data_change'),

    # login view
    path('login/', views.UserLoginView.as_view(), name='login'),

    # password change view
    path('password-change/', views.PasswordChange.as_view(), name='password_change'),

    # exit
    path('exit/', views.ExitView.as_view(), name='exit'),

]

medical_visit/urls.py
# django library
from django.urls import path

# my views
from medical_visit import views


app_name='medical_visit'

urlpatterns = [
    path('medical-add/', views.MedicalAddView.as_view(), name='medical_add_view'),
    path('medical-staff/<int:patient_id>/<slug:spec>/', views.MedicalView.as_view(), name='medical_staff_view'),
    path('visit-date-register/<int:patient_id>/<slug:spec>/<int:medical_id>/', views.VisitDateView.as_view(), name='visit_date_register'),
    path('visit-hour-register/<int:patient_id>/<slug:spec>/<int:medical_id>/<date_of_visit>/', views.VisitHourView.as_view(), name='visit_hour_register'),
    path('visit-delete/<int:patient_id>/', views.VisitDeleteView.as_view(), name='visit_delete'),
    ]

medical_visit/models.py
# django library
from django.db import models
from django.urls import reverse

# my models
from registration.models import Patient


# Create your models here.


class Specialization(models.Model):
    type_of_specialization = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, db_index=True, unique=True, help_text='A short label, generally used in URLs')
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('type_of_specialization',)

    def __str__(self):
        return self.type_of_specialization


class Medical(models.Model):
    specialization = models.ForeignKey(Specialization, on_delete=models.DO_NOTHING,)
    forename = models.CharField(max_length=200)
    surname = models.CharField(max_length=200)
    email = models.EmailField(blank=True)
    consulting_room = models.IntegerField(unique=True)
    nickname = models.CharField(max_length=200, unique=True)
    presence = models.BooleanField(default=True)

    class Meta:
        ordering = ('surname', 'specialization')

    def __str__(self):
        return '{} {}'.format(self.surname, self.forename)

    def get_absolute_url(self):
        return reverse('medical_user_data_change', args=[self.id])


class MedicalVisit(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.DO_NOTHING, related_name='patients')
    doctor = models.ForeignKey(Medical, on_delete=models.DO_NOTHING, related_name='doctors')
    date_of_visit = models.DateField()
    hour_of_visit = models.CharField(max_length=10,)

    def __str__(self):
        frm = (self.doctor.forename,
               self.doctor.surname,
               self.patient.first_name,
               self.patient.last_name,
               self.date_of_visit,
               self.hour_of_visit)
        return 'Dr {} {}, patient: {} {}, date: {}, hour: {}'.format(*frm)

    def get_absolute_url(self):
        return reverse('medical_advice:advice_description', args=[self.doctor.nickname, self.patient.id])

medical_visit/forms.py
# standard library
from django import forms
from datetime import date

# django core
from django.core.validators import MinValueValidator

# django_datetime widget
from datetimewidget.widgets import DateWidget

# my models
from medical_visit.models import Medical, Specialization, MedicalVisit



# Create your forms here


dateOptions = {'format': 'yyyy-mm-dd', 'autoclose': 'true', 'showMeridian': 'false', 'weekStart': 1, 'todayBtn': 'true'}


class MedicalAddForm(forms.ModelForm):
    specialization = forms.ModelChoiceField(queryset=Specialization.objects.filter(active=True), label='Specialization')
    email = forms.EmailField(label='E-mail')
    class Meta:
        model = Medical
        fields = ('specialization', 'forename', 'surname', 'email', 'consulting_room')



class SpecializationForm(forms.ModelForm):
    type_of_specialization = forms.ModelChoiceField(queryset=Specialization.objects.filter(active=True),
                                                    widget=forms.RadioSelect,
                                                    empty_label=None,
                                                    label='Choice specialization for proceed registration...')

    class Meta:
        model = Specialization
        fields = ('type_of_specialization',)



class DateVisitRegisterForm(forms.ModelForm):
    date_of_visit = forms.DateField(widget=DateWidget(options=dateOptions, bootstrap_version=3), initial=date.today())

    class Meta:
        model = MedicalVisit
        fields = ('date_of_visit',)

medical_visit/views.py
# standart library
from datetime import datetime, date, time

# django library
from django.urls import reverse
from django.contrib import messages
from django.views.generic import View
from django.contrib.auth.models import User
from django.shortcuts import render, HttpResponseRedirect

# my models
from registration.models import Patient
from account.models import Profile, ProfessionalGroup
from medical_visit.models import Medical, Specialization, MedicalVisit

# my forms
from medical_visit.forms import DateVisitRegisterForm, MedicalAddForm

# my functions
from functions.myfunctions import visits_list, holidays, diacritical_remover


# Create your views here.


# adding new medical view
class MedicalAddView(View):

    def get(self, request):
        conrooms = Medical.objects.values_list('consulting_room', flat=True)
        if conrooms:
            conrooms = max(list(conrooms)) + 1
        else:
            conrooms = 1
        form = MedicalAddForm(initial={'consulting_room': conrooms})

        return render(request, 'medical_visit/medical_add.html', {'form': form})

    def post(self, request):
        kwargs, nickname, password, medical = None, None, None, None

        if len(request.POST) > 1:
            form = MedicalAddForm(data=request.POST)

            if form.is_valid():
                cd = form.cleaned_data
                specialization = cd['specialization']
                forename = cd['forename']
                surname = cd['surname']
                email = cd['email']
                consulting_room = cd['consulting_room']

                kwargs = {'email': email,
                          'surname': surname,
                          'forename': forename,
                          'specialization': specialization,
                          'consulting_room': consulting_room}

                new_medical = Medical.objects.create(**kwargs)

                if new_medical.id:
                    # create credentials for new medicals
                    strid = str(new_medical.id)
                    medical = Medical.objects.get(id=new_medical.id)

                    if new_medical.id > 0 and new_medical.id <= 9:
                        strid = '0' + str(new_medical.id)

                    nickname = ''.join([medical.forename[:2], medical.surname[:2], str(medical.specialization)[:2], strid]).lower()
                    password = ''.join([str(medical.specialization), strid]).lower()
                    nickname = diacritical_remover(nickname)
                    password = diacritical_remover(password)

                    if nickname and password:

                        Medical.objects.filter(id=new_medical.id).update(nickname=nickname)
                        user=User.objects.create_user(username=nickname,
                                                      password=password,
                                                      email=new_medical.email,
                                                      first_name=new_medical.forename,
                                                      last_name=new_medical.surname)
                        group = ProfessionalGroup.objects.get(slug='medical-staff')
                        Profile.objects.create(user=user, group=group)

                kwargs['medical'] = medical
                kwargs['nickname'] = nickname
                kwargs['password'] = password

                return render(request, 'medical_visit/medical_add.html', kwargs)

            else:

                conrooms = Medical.objects.values_list('consulting_room', flat=True)

                return render(request, 'medical_visit/medical_add.html', {'conrooms': max(list(conrooms))})


# medical's register visit view
class MedicalView(View):

    def get(self, request, patient_id, spec):
        specialization = Specialization.objects.get(slug=spec)
        patient = Patient.objects.get(id=patient_id)
        medicals = Medical.objects.filter(specialization=specialization).order_by('surname')
        # li = Medical.objects.filter(email__contains='onet')
        # cs = Medical.objects.filter(consulting_room__gte=7)
        # cg = Medical.objects.filter(consulting_room__gte=2,consulting_room__lte=10)
        for medical in medicals:
            user = User.objects.get(username=medical.nickname)
            if user.is_active == False:
                medicals = medicals.exclude(pk=medical.id)
        visits = visits_list(patient=patient, date_of_visit__gte=date.today())

        if not medicals.exists():
            msg = r'No doctors in selected specialization ({})'
            messages.error(request, msg.format(spec))
            kwargs={'patient_id':patient_id}
            return HttpResponseRedirect(reverse('registrations:register_patient_detail', kwargs=kwargs))
        else:
            context = {'spec': spec,
                       'visits': visits,
                       'patient': patient,
                       'medicals': medicals,
                       'patient_id': patient_id}
            return render(request, 'medical_visit/medical_staff_list.html', context)


    def post(self, request, patient_id, spec):

        if len(request.POST) > 1:
            medical_id = request.POST['medical_id']
            kwargs = {'spec': spec, 'medical_id': medical_id, 'patient_id': patient_id}
            return HttpResponseRedirect(reverse('medical_visit:visit_date_register', kwargs=kwargs))

        else:
            msg = r'Please select doctor name'
            messages.error(request, msg)
            kwargs={'spec': spec, 'patient_id':patient_id}
            return HttpResponseRedirect(reverse('medical_visit:medical_staff_view', kwargs=kwargs))


# booking data visit view
class VisitDateView(View):

    def get(self, request, patient_id, spec, medical_id):
        form = DateVisitRegisterForm()
        patient = Patient.objects.get(id=patient_id)
        medical = Medical.objects.get(id=medical_id)
        visits = visits_list(patient=patient, date_of_visit__gte=date.today())
        context = {'spec': spec,
                   'form': form,
                   'visits': visits,
                   'patient': patient,
                   'medical': medical,
                   'patient_id': patient_id,}
        return render(request, 'medical_visit/visit_date_register.html', context)

    def post(self, request, patient_id, spec, medical_id):
        kwargs={'spec': spec,
                'patient_id': patient_id,
                'medical_id': medical_id}

        if len(request.POST) > 1:
            form = DateVisitRegisterForm(data=request.POST)

            if form.is_valid():
                cd = form.cleaned_data
                date_of_visit = cd['date_of_visit']

                if date_of_visit >= date.today():
                    if date_of_visit.weekday() < 5:
                        if date_of_visit not in holidays(date_of_visit).values():
                            date_of_visit = datetime.strftime(date_of_visit,'%Y-%m-%d')
                            kwargs['date_of_visit'] = date_of_visit
                            return HttpResponseRedirect(reverse('medical_visit:visit_hour_register', kwargs=kwargs))
                        else:
                            msg =r'Selected date is a holiday ({}). Please select correct date!'
                            for key, value in holidays(date_of_visit).items():
                                if value == date_of_visit:
                                    messages.error(request, msg.format(key))
                    else:
                        if date_of_visit.weekday() == 5:
                            msg =r'Selected date is a Saturday... Please select correct date!'
                            messages.error(request, msg)
                        else:
                            msg =r'Selected date is a Sunday... Please select correct date!'
                            messages.error(request, msg)

                else:
                    msg = r"Please select today's or future date..."
                    messages.error(request, msg)

                return HttpResponseRedirect(reverse('medical_visit:visit_date_register', kwargs=kwargs))

            else:
                msg = r'Please select a valid visit date...'
                messages.error(request, msg)

                return HttpResponseRedirect(reverse('medical_visit:visit_date_register', kwargs=kwargs))

# booking hour visit view
class VisitHourView(View):

    def get(self, request, patient_id, spec, medical_id, date_of_visit):
        # hours of visit
        hours, minutes = (8,12), (0,41,20)
        # permanent hours of medical visits list = phomv_list
        phomv_list = [str(time(x,y)) for x in range(*hours) for y in range(*minutes)]
        patient = Patient.objects.get(id=patient_id)
        doctor = Medical.objects.get(id=medical_id)
        doc_visit_list = visits_list(doctor=doctor, date_of_visit=date_of_visit)
        visit_hour_list = visits_list(patient_id=patient_id, date_of_visit=date_of_visit)
        visits = MedicalVisit.objects.filter(patient=patient, date_of_visit=date_of_visit)
        valid_hour_list = {}

        if visits:
            for visit in visits:
                if visit.doctor.id != int(medical_id) and str(visit.doctor.specialization) == spec:
                    visit_hour_list.remove(visit.hour_of_visit)
                    valid_hour_list = set(visit_hour_list + doc_visit_list)
                    valid_hour_list = sorted(list(valid_hour_list))

                else:
                    valid_hour_list = set(visit_hour_list + doc_visit_list)
                    valid_hour_list = sorted(list(valid_hour_list))
        else:
            valid_hour_list = doc_visit_list

        visits = visits_list(patient=patient, date_of_visit__gte=date.today())
        date_of_visit = datetime.strptime(date_of_visit, '%Y-%m-%d')
        date_of_visit = date_of_visit.date()
        context = {'spec': spec,

templates/medical_visit/delete_visits.html
{% extends "base.html" %}
{% load bootstrap3 %}


{% block title %}Patient visits remove{% endblock %}


{% block content %}

    <div class="container">
        <div class="row well" style="background-color: bisque">
            <h1 class="text-center">Small Clinic</h1>
            <p class="text-center">Application to handle small clinics</p>
            {% include 'blocks/patient_data.html' %}
            <div class="col-lg-6">
                <h4 class="text-center well" style="background-color: aquamarine"><strong style="color: crimson">VISITS</strong></h4>
                <blockquote>
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-sm-12">
                                <table class="table table-hover">
                                    <tbody>
                                        {% for visit in visits %}
                                            <tr>
                                                <td><label style="color: crimson"><input type="checkbox" name="visit" value="{{ visit.id }}"> {{ visit.doctor }} ({{ visit.doctor.specialization }}), {{ visit.date_of_visit|date:"d.m.Y" }}, {{ visit.hour_of_visit }}</label></td>
                                            </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                                <br>
                                {% if visits %}
                                    <div class="btn-group btn-group-md">
                                        <button type="submit" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span> Delete</button>
                                        <a class="btn btn-primary" href="{% url 'registrations:register_patient_detail' patient_id %}"><span class="glyphicon glyphicon-step-backward"></span> Back to register</a>
                                    </div>
                                {% else %}
                                    <h4 style="color: crimson"><strong>Caution!<br><br>No visit(s) for today and on future are registred!!!</strong><br><br></h4>
                                    <div class="btn-group btn-group-md">
                                        <a class="btn btn-info" href="{% url 'registrations:register_patient_detail' patient_id %}"><span class="glyphicon glyphicon-step-backward"></span> Back to register</a>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    </form>
                </blockquote>
            </div>
        </div>
    </div>

{% endblock %}

templates/medical_visit/medical_add.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}

    <div class="container">
        <div class="row well" style="background-color: bisque">
            <h1 class="text-center">Small Clinic</h1>
            <p class="text-center">Application to handle small clinics</p>

            <div class="col-lg-6">
                {% if form %}
                    <h4 class="text-center well" style="background-color: aquamarine"><strong style="color: crimson">MEDICALS ADD FORM</strong></h4>
                    <blockquote>
                        <h4 style="color: darkgreen"><strong style="border-bottom: double 3px;">Please input new medical's data...</strong></h4><hr>
                        <form action="" method="post">
                            {% csrf_token %}
                                {% bootstrap_field form.specialization %}
                                {% bootstrap_field form.forename placeholder='Input forename of medical' %}
                                {% bootstrap_field form.surname placeholder='Input surname of medical' %}
                                {% bootstrap_field form.email placeholder='Input a valid email of medical' %}
                                {% bootstrap_field form.consulting_room placeholder='Input number of consulting_room' %}
                            <div class="btn-group btn-group-lg">
                                <a class="btn btn-primary" href="{% url 'admin_site' %}"><span class="glyphicon glyphicon-step-backward"></span> Back to admin dashboard</a>
                                <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-ok"></span> Confirm</button>
                            </div>
                        </form>
                    </blockquote>
                {% else %}
                    {% if medical %}
                        <h4 class="text-center well" style="background-color: aquamarine"><strong style="color: crimson">NEW DATA OF DOCTOR</strong></h4>
                        <blockquote>
                            <table class="table">
                                <tbody>
                                    <tr>
                                        <td><strong>Forename: </strong></td><td><code class="lead">{{ forename }}</code></td>
                                    </tr>
                                    <tr>
                                        <td><strong>Surname: </strong></td><td><code class="lead">{{ surname }}</code></td>
                                    </tr>
                                    <tr>
                                        <td><strong>Specialization: </strong></td><td><code class="lead">{{ specialization }}</code></td>
                                    </tr>
                                    <tr>
                                        <td><strong>Consulting room: </strong></td><td><code class="lead">{{ consulting_room }}</code></td>
                                    </tr>
                                    <tr>
                                        <td><strong>E-mail: </strong></td><td><code class="lead"><a href="mailto:{{ email }}?subject=Potwierdzamy rejestrację w bazie danych Small-Clinic?body=Potwierdzamy rejestrację: Imię i nazwisko: {{ forename }} {{ surname }}; Specialization: {{ specialization }}; Consulting room: {{ consulting_room }}; Nickname: {{ nickname }}; Password: {{ password }}" target="_top">{{ email }}</a></code></td>
                                    </tr>
                                </tbody>
                            </table>
                        </blockquote>
                    {% else %}
                        <h4 class="text-center well" style="background-color: aquamarine"><strong style="color: crimson">NEW DATA OF DOCTOR</strong></h4>
                        <blockquote>
                            <p class="lead text-justify">The consulting room is not avaiable. Please back to the form and input  consulting room number grower then {{ conrooms }}.</p>
                            <div class="btn-group btn-group-lg btn-group-justified">
                                <a class="btn btn-danger" href="{% url 'medical_visit:medical_add_view' %}"><span class="glyphicon glyphicon-step-backward"></span> Back to form...</a>
                            </div>
                    {% endif %}
                {% endif %}
            </div>
            <div class="col-lg-6">
                <h4 class="text-center well" style="background-color: aquamarine"><strong style="color: crimson">GENERATED MEDICAL CREDENTIALS</strong></h4>
                <blockquote>
                    {% if nickname and password %}
                        <table class="table">
                            <tbody>
                                <tr>
                                    <td><strong>Nickname: </strong></td><td><code class="lead">{{ nickname }}</code></td>
                                </tr>
                                <tr>
                                    <td><strong>Password: </strong></td><td><code class="lead">{{ password }}</code></td>
                                </tr>
                            </tbody>
                        </table>
                        <div class="btn-group btn-group-lg">
                            <a class="btn btn-primary" href="{% url 'index' %}"><span class="glyphicon glyphicon-step-backward"></span> Back to login...</a>
                            <a class="btn btn-info btn-lg" href="{% url 'medical_visit:medical_add_view' %}"><span class="glyphicon glyphicon-heart"></span> Add new doctor</a>
                        </div>
                    {% else %}
                        <h4 style="color: darkgreen"><strong style="border-bottom: double 3px;">There are no data to show...</strong></h4><hr>
                        <div class="btn-group btn-group-lg">
                            <a class="btn btn-primary" href="{% url 'index' %}"><span class="glyphicon glyphicon-step-backward"></span> Back to login...</a>
                        </div>
                    {% endif %}
                </blockquote>
            </div>
        </div>
    </div>

{% endblock %}

templates/medical_visit/medical_presence_view.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load i18n %}


{% block title %}Patient register{% endblock %}

{% block content %}
    <div class="container">
        <div class="row well" style="background-color: bisque">
            <h1 class="text-center">Small Clinic</h1>
            <p class="text-center">Application to handle small clinics</p>
            {% include 'blocks/medical_presence_buttons.html' %}
            <div class="col-lg-6">
                <h4 class="text-center well" style="background-color: aquamarine"><strong style="color: crimson">MEDICALS PRESENCE</strong></h4>
                <blockquote>
                    <form action="" method="post">
                        {% csrf_token %}
                        {% for medical in medicals %}
                            <div class="checkbox">
                                {% if medical.presence %}
                                    <code><label><input type="checkbox" name="presence" value="{{ medical.id }}" checked> {{ medical.forename }} {{ medical.surname }}</label></code><br>
                                {% else %}
                                    <code><label style="color: darkgrey"><input type="checkbox" name="presence" value="{{ medical.id }}"> {{ medical.forename }} {{ medical.surname }} (absent)</label></code><br>
                                {% endif %}
                            </div>
                        {% endfor %}

                        {% if medicals %}
                            <div class="btn-group btn-group-md">
                                <a class="btn btn-info" href="{% url 'registrations:register' %}"><span class="glyphicon glyphicon-step-backward"></span> Back to patient's list</a>
                                <button type="submit" class="btn btn-danger"><span class="glyphicon glyphicon-refresh"></span> Confirm</button>
                            </div>
                        {% else %}
                            <h4 style="color: crimson"><strong>Caution!<br><br>Please select a medical specialization</strong><br><br></h4>
                            <div class="btn-group btn-group-md">
                            <a class="btn btn-info" href="{% url 'registrations:register' %}"><span class="glyphicon glyphicon-step-backward"></span> Back to patient's list</a>
                        </div>
                        {% endif %}
                    </form>
                </blockquote>
            </div>
        </div>
    </div>
{% endblock %}

templates/medical_visit/medical_staff_list.html
{% extends "base.html" %}
{% load bootstrap3 %}


{% block title %}Patient register{% endblock %}


{% block content %}

    <div class="container">
        <div class="row well" style="background-color: bisque">
            <h1 class="text-center">Small Clinic</h1>
            <p class="text-center">Application to handle small clinics</p>
            {% include 'blocks/patient_data.html' %}
            <div class="col-lg-6">
                <h4 class="text-center well" style="background-color: aquamarine"><strong style="color: crimson">SPECIALIZATION: {{ spec|capfirst }}</strong></h4>
                <blockquote>
                    <form action="" method="post">
                        {% csrf_token %}
                        <table class="table table-hover">
                            <tbody>
                                {% for medical in medicals %}
                                    {% if medical.presence %}
                                        <tr>
                                            <td align="right">{{ forloop.counter }}.</td><td><strong><label style="color: crimson"><input type="radio" name="medical_id" value="{{ medical.id }}"> {{ medical.forename }} {{ medical.surname }}</label></strong></td>
                                        </tr>
                                    {% else %}
                                        <tr>
                                            <td align="right">{{ forloop.counter }}</td><td><strong><label style="color: darkgrey"><input type="radio" name="medical_id" value="{{ medical.id }}" disabled> {{ medical.forename }} {{ medical.surname }} (absent)</label></strong></td>
                                        </tr>
                                    {% endif %}
                                {% endfor %}
                            </tbody>
                        </table>
                        <div class="btn-group">
                            <a class="btn btn-primary" href="{% url 'registrations:register_patient_detail' patient_id %}"><span class="glyphicon glyphicon-step-backward"></span> Back to specialization choice</a>
                            <button type="submit" class="btn btn-md btn-success"><span class="glyphicon glyphicon-ok"></span> Confirm</button>
                        </div>
                    </form>
                </blockquote>
            </div>
        </div>
    </div>

{% endblock %}

templates/medical_visit/visit_date_register.html
{% extends "base.html" %}
{% load bootstrap3 %}


{% block title %}Patient register{% endblock %}


{% block content %}

    <div class="container">
        <div class="row well" style="background-color: bisque">
            <h1 class="text-center">Small Clinic</h1>
            <p class="text-center">Application to handle small clinics</p>
            {% include 'blocks/patient_data.html' %}
            <div class="col-lg-6">
                <h4 class="text-center well" style="background-color: aquamarine"><strong style="color: crimson">SPECIALIZATION: {{ spec|capfirst }}</strong></h4>
                <blockquote>
                    <form action="" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-sm-8">
                                <h4 style="color: darkgreen"><strong style="border-bottom: double 3px;">Your choice</strong><br><br>Medical name:<strong> {{ medical.forename }} {{ medical.surname }}</strong><br>consulting room:<strong> {{ medical.consulting_room }}</strong></h4><hr>
                                {% for field in form %}
                                    {% bootstrap_field form.date_of_visit placeholder='Choose date of visit' %}
                                {% endfor %}
                                <div class="btn-group btn-group-md">
                                    <a class="btn btn-primary" href="{% url 'medical_visit:medical_staff_view' patient_id spec %}"><span class="glyphicon glyphicon-step-backward"></span> Back to medicals choice</a>
                                    <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-ok"></span> Confirm</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </blockquote>
            </div>
        </div>
    </div>

{% endblock %}