account/urls.py
# django library
from django.urls import path

# my views
from account import views


urlpatterns = [

    # admin view
    path('admin-site/', views.AdminView.as_view(), name='admin_site'),

    # create user view
    path('create-user/', views.CreateNewUser.as_view(), name='create_user'),

    # change medical user data
    path('medical-user-data-change/<int:md_id>/', views.MedicalUserDataChange.as_view(), name='medical_user_data_change'),

    # login view
    path('login/', views.UserLoginView.as_view(), name='login'),

    # password change view
    path('password-change/', views.PasswordChange.as_view(), name='password_change'),

    # exit
    path('exit/', views.ExitView.as_view(), name='exit'),

]

medical_advice/urls.py
# django library
from django.urls import path

# my views
from medical_advice import views

app_name='medical_advice'

urlpatterns = [
    path('advice/<username>/', views.MedicalAdviceView.as_view(), name='advice'),
    path('advice-description/<username>/<int:patient_id>/', views.AdviceDescriptionView.as_view(), name='advice_description'),
    path('medical-prescription/<username>/<int:patient_id>/', views.MedicalPrescriptionDetailView.as_view(), name='medical_prescription_detail'),
    path('medical-prescription/email/pdf/<username>/<int:patient_id>/', views.MedicalPrescriptionSender.as_view(), name='medical_prescription_pdf'),
    ]

medical_visit/urls.py
# django library
from django.urls import path

# my views
from medical_visit import views


app_name='medical_visit'

urlpatterns = [
    path('medical-add/', views.MedicalAddView.as_view(), name='medical_add_view'),
    path('medical-staff/<int:patient_id>/<slug:spec>/', views.MedicalView.as_view(), name='medical_staff_view'),
    path('visit-date-register/<int:patient_id>/<slug:spec>/<int:medical_id>/', views.VisitDateView.as_view(), name='visit_date_register'),
    path('visit-hour-register/<int:patient_id>/<slug:spec>/<int:medical_id>/<date_of_visit>/', views.VisitHourView.as_view(), name='visit_hour_register'),
    path('visit-delete/<int:patient_id>/', views.VisitDeleteView.as_view(), name='visit_delete'),
    ]

templates/blocks/hour_forms.html
<style>
    label:hover {
        background-color: lightcyan;
    }
</style>


    <form action="" method="post">
        {% csrf_token %}
        <div class="col-sm-4 text-center">
            <!-- permanent hours of medical visits list = phomv_list-->
            {% for hour in phomv_list %}
                {% if hour in valid_hour_list %}
                    <code class="lead"><label style="color: darkgrey"><input type="radio" name="hour_of_visit" value="{{ hour }}" disabled> {{ hour }}</label></code><br>
                {% else %}
                    <code class="lead"><label><input type="radio" name="hour_of_visit" value="{{ hour }}"> {{ hour }}</label></code><br>
                {% endif %}
            {% endfor %}
            {% if valid_hour_list == phomv_list %}
                <div class="btn-group btn-group-sm">
                    <a class="btn btn-danger" href="{% url 'medical_visit:medical_staff_view' patient_id spec %}"><span class="glyphicon glyphicon-step-backward"></span> Back to doctor choice</a>
                </div>
            {% else %}
                <div class="btn-group btn-group-lg">
                    <button type="submit" class="btn btn-success"><span class="glyphicon glyphicon-ok"></span> Confirm</button>
                </div>
            {% endif %}
        </div>
    </form>

templates/blocks/medical_prescription.html
{% load utility_tags %}
{% load static %}

  <style>
      .tab {
    	    border:2px solid black;
    	    width:530px;
    	    border-collapse:collapse;
            font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
            }
      .tab tr td {
    	    padding: 5px;
    	    color: black;
    	    }
      .border-right {
    	    border-right:2px solid black;
    	    }
      .border-bottom {
    	    border-bottom:2px solid black;
    	    }
        .dash {
    	    border-right:1px dashed black;
    	    border-bottom:1px dashed black;
    	    }
        @media print {
            #printButton {
            display: none;}
            }
        .crop_clinic {
            width: 250px;
            height: 50px;
            overflow: hidden;
        }
        .crop_med {
            width: 180px;
            height: 40px;
            overflow: hidden;
        }
    </style>

    <div class="col-sm-4">
        <table class="tab">
            <tr>
                <td width="80"><strong><small>Recepta {{ advice.id }}</small></strong></td>
                <td width="450"></td>
            </tr>
            <tr>
                <td colspan="2"></td>
            </tr>
            <tr>
                <td colspan="2"><div align="center"><h1>SMALL CLINIC</h1></div></td>
            </tr>
            <tr>
                <td colspan="2"><div align="center"><strong>Application for handle small clinic</strong></div></td>
            </tr>
            <tr>
                <td colspan="2"></td>
            </tr>
            <tr>
                <td colspan="2"></td>
            </tr>
            <tr>
                <td colspan="2"></td>
            </tr>
            <tr>
                <td colspan="2"></td>
            </tr>
            <tr>
                <td colspan="2"></td>
            </tr>
            <tr>
                <td><strong><small>Świadczeniodawca:</small></strong></td><td><img src="{% static 'images/barcode_svg.svg' %}" class="crop_clinic"></td>
            </tr>
        </table>
        <table class="tab">
            <tr>
                <td class="border-right" width="330"><strong><small>Pacjent</small></strong></td>
                <td  width="200"><strong><small>Oddział NFZ</small></strong></td>
            </tr>
            <tr>
                <td class="border-right">{{ patient.first_name }} {{ patient.last_name }}</td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td class="border-right">{{ patient.postal }} {{ patient.city }}</td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td class="border-right">{{ patient.street }}</td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td class="border-right">&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td class="border-right">&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td class="border-right">&nbsp;</td>
                <td><strong>&nbsp;</strong></td>
            </tr>
            <tr>
                <td class="border-right"><small><strong>Pesel: </strong>{{ patient.birthday|pesel }}</small></td>
                <td><strong><small>Uprawnienia dodatkowe:</small></strong></td>
            </tr>
        </table>
        <table class="tab" >
            <tr>
                <td width="330" class="dash"><strong><small>Rp</small></strong></td>
                <td width="200" class="dash"><strong><small>Odpłatność</small></strong></td>
            </tr>
            {% for medicine in medicines %}
                <tr>
                    <td class="dash">{{ medicine }}</td>
                    <td class="dash">{{ advice.discount }}</td>
                </tr>
            {% endfor %}

            {% if medicines|length == 1 %}
                <tr>
                    <td class="dash">&nbsp;</td>
                    <td class="dash">&nbsp;</td>
                </tr>
                <tr>
                    <td class="dash">&nbsp;</td>
                    <td class="dash">&nbsp;</td>
                </tr>
                <tr>
                    <td class="dash">&nbsp;</td>
                    <td class="dash">&nbsp;</td>
                </tr>
                <tr>
                    <td class="dash">&nbsp;</td>
                    <td class="dash">&nbsp;</td>
                </tr>
                <tr>
                    <td class="dash">&nbsp;</td>
                    <td class="dash">&nbsp;</td>
                </tr>
            {% elif medicines|length == 2 %}
                <tr>
                    <td class="dash">&nbsp;</td>
                    <td class="dash">&nbsp;</td>
                </tr>
                <tr>
                    <td class="dash">&nbsp;</td>
                    <td class="dash">&nbsp;</td>
                </tr>
                <tr>
                    <td class="dash">&nbsp;</td>
                    <td class="dash">&nbsp;</td>
                </tr>
                <tr>
                    <td class="dash">&nbsp;</td>
                    <td class="dash">&nbsp;</td>
                </tr>
            {% elif medicines|length == 3 %}
                <tr>
                    <td class="dash">&nbsp;</td>
                    <td class="dash">&nbsp;</td>
                </tr>
                <tr>
                    <td class="dash">&nbsp;</td>
                    <td class="dash">&nbsp;</td>
                </tr>
                <tr>
                    <td class="dash">&nbsp;</td>
                    <td class="dash">&nbsp;</td>
                </tr>
            {% endif %}
            <tr><td rowspan="4" class="dash">&nbsp;</td><td>&nbsp;</td></tr>
            <tr><td>&nbsp;</td></tr>
            <tr><td>&nbsp;</td></tr>
        </table>
        <table class="tab">
            <tr>
                <td width="330" class="border-right"><strong><small>Data wystawienia:</small></strong></td>
                <td width="200"><strong><small>Dane i podpis lekarza</small></strong></td>
            </tr>
            <tr>
                <td class="border-right">{{ visit.date_of_visit|date:'d.m.Y' }}</td>
                <td>Spec: {{ doctor.specialization.type_of_specialization }}</td>
            </tr>
            <tr>
                <td class="border-right border-bottom">&nbsp;</td>
                <td>Imię: {{ doctor.forename }}</td>
            </tr>
            <tr>
                <td class="border-right"><strong><small>Data realizacji &quot;od dnia&quot;:</small></strong></td>
                <td>Nazwisko: {{ doctor.surname }}</td>
            </tr>
            <tr>
                <td class="border-right">{{ now|realization }}</td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td class="border-right">&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td class="border-right">&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td class="border-right">&nbsp;</td>
                <td><img src="{% static 'images/barcode_med.svg' %}" class="crop_med"></td>
            </tr>
            <tr>
                <td class="border-right">&nbsp;</td>
                <td><strong><small>Dane podmiotu drukującego:</small></strong></td>
            </tr>
        </table>
    </div>

templates/blocks/medical_presence_buttons.html
<div class="col-lg-6">
    <h4 class="text-center well" style="background-color: aquamarine"><strong style="color: crimson">CHOICE SPECIALIZATION</strong></h4>
    <blockquote>
        <div class="btn-group-vertical">
            <a class="btn btn-primary btn-lg" href="{% url 'registrations:medical_presence' spec='dentist' %}">Dentist</a>
            <a class="btn btn-success btn-lg" href="{% url 'registrations:medical_presence' spec='internist' %}">Internist</a>
            <a class="btn btn-warning btn-lg" href="{% url 'registrations:medical_presence' spec='laryngologist' %}">Laryngologist</a>
            <a class="btn btn-info btn-lg" href="{% url 'registrations:medical_presence' spec='ophthalmologist' %}">Ophthalmologist</a>
            <a class="btn btn-danger btn-lg" href="{% url 'registrations:medical_presence' spec='pediatrician' %}">Pediatrician</a>
        </div>
    </blockquote>
</div>

templates/blocks/patient_data.html
<div class="col-lg-6">
    <h4 class="text-center well" style="background-color: aquamarine"><strong style="color: crimson">PATIENT REGISTER</strong></h4>
    <blockquote>
        <table class="table table-hover">
            <tbody>
                <tr>
                    <td><strong>Forename: </strong></td><td><strong style="color: crimson">{{ patient.first_name }}</strong></td>
                </tr>
                <tr>
                    <td><strong>Surname: </strong></td><td><strong style="color: crimson">{{ patient.last_name }}</strong></td>
                </tr>
                <tr>
                    <td><strong>Birthday: </strong></td><td><strong style="color: crimson">{{ patient.birthday|date:"l, j F Y" }}</strong></td>
                </tr>
                <tr>
                    <td><strong>City: </strong></td><td><strong style="color: crimson">{{ patient.postal }} {{ patient.city }}</strong></td>
                </tr>
                <tr>
                    <td><strong>Street: </strong></td><td><strong style="color: crimson">ul. {{ patient.street }}</strong></td>
                </tr>
                <tr>
                    <td><strong>Phone: </strong></td><td><strong style="color: crimson">{{ patient.phone }}</strong></td>
                </tr>
                <tr>
                    <td><strong>Email: </strong></td><td><strong><a href="mailto:{{ patient.email }}?subject=Your medical visit?body=Potwierdzamy wizytę: Imię i nazwisko: {{ patient.first_name }} {{ patient.last_name }}; Lekarz: {{ medical.forename }} {{ medical.surname }}; Data wizyty: {{ date_of_visit|date:"F j, Y" }}; Godzina wizyty: {{ hour_of_visit }}; Gabinet: {{ medical.consulting_room }}" target="_top">{{ patient.email }}</a></strong></td>
                </tr>
                <tr>
                    <td><strong>Ensured: </strong></td><td><strong style="color: crimson">{% if patient.ensured %}Yes{% else %}No{% endif %}</strong></td>
                </tr>
            </tbody>
        </table>
        {% if patient.ensured and visits %}
            <div class="btn-group btn-group-md">
                <a class="btn btn-warning" href="{% url 'registrations:change_data_patient' patient_id %}"><span class="glyphicon glyphicon-user"></span> Change patient's data</a>
                <a class="btn btn-primary" href="{% url 'registrations:register' %}"><span class="glyphicon glyphicon-step-backward"></span> Back to patients list</a>
                <a class="btn btn-danger" href="{% url 'medical_visit:visit_delete' patient_id %}"><span class="glyphicon glyphicon-remove"></span> Visits</a>
            </div>
        {% else %}
            <div class="btn-group btn-group-md">
                <a class="btn btn-warning" href="{% url 'registrations:change_data_patient' patient_id %}"><span class="glyphicon glyphicon-user"></span> Change patient's data</a>
                <a class="btn btn-primary" href="{% url 'registrations:register' %}"><span class="glyphicon glyphicon-step-backward"></span> Back to patients list</a>
                <a class="btn btn-danger" href="#" disabled><span class="glyphicon glyphicon-remove"></span> Visits</a>
            </div>
        {% endif %}
    </blockquote>
</div>

templates/blocks/prescription_detail_button.html
<div class="col-sm-4">
    <div class="btn-group-vertical btn-group-md pull-right">
        <a id="printButton" class="btn btn-success" href="#" onclick="window.print();"><span class="glyphicon glyphicon-print"></span> Print...</a>
        {% if patient.email %}
            <a id="printButton" class="btn btn-danger" href="{% url 'medical_advice:medical_prescription_pdf' doctor.nickname patient.id %}"><span class="glyphicon glyphicon-send"></span> E-mail to patient</a>
        {% else %}
            <a id="printButton" class="btn btn-danger" disabled><span class="glyphicon glyphicon-send"></span> E-mail to patient</a>
        {% endif %}
        <a id="printButton" class="btn btn-primary" href="{% url 'medical_advice:advice' doctor.nickname %}"><span class="glyphicon glyphicon-step-backward"></span> Back to patient list</a>
    </div>
</div>